# TYPE  DATABASE      USER          ADDRESS         METHOD
local   all           postgres                      trust
local   all           all                           reject
host    supermarket   market_app    samenet          scram-sha-256
host    supermarket   market_admin  samenet          scram-sha-256
host    supermarket   postgres     127.0.0.1/32      scram-sha-256
host    supermarket   all           0.0.0.0/0        scram-sha-256
host    supermarket   all           ::0/0            scram-sha-256
host    all           all           0.0.0.0/0        reject
host    all           all           ::0/0            reject
